import type { Metadata } from "next";
import { Breadcrumbs, buildBreadcrumbSegments } from "@/components/landing/breadcrumbs";
import { CtaSection } from "@/components/landing/cta-section";
import { LegalSection } from "@/components/landing/legal-section";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "OpenZync privacy policy — how we collect, use, and protect your data.",
  alternates: { canonical: "/privacy" },
};

/**
 * Privacy Policy page — clean legal typography with sections.
 */
export default function PrivacyPage() {
  const segments = buildBreadcrumbSegments("/privacy");

  return (
    <>
      <section className="pt-36 pb-16">
        <div className="mx-auto max-w-3xl px-6">
          <Breadcrumbs segments={segments} />
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-4">
            Privacy Policy
          </h1>
          <p className="text-surface-500 text-sm mb-8">Last updated: March 15, 2026</p>
        </div>
      </section>

      <section className="pb-20">
        <div className="mx-auto max-w-3xl px-6 prose-custom">
          <LegalSection title="Introduction">
            <p>
              OpenZync (&ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;) is committed to protecting
              your privacy. This Privacy Policy explains how we collect, use, disclose, and
              safeguard your information when you visit our website and use our services.
            </p>
          </LegalSection>

          <LegalSection title="Information We Collect">
            <p>We may collect the following types of information:</p>
            <ul>
              <li>
                <strong>Account Information:</strong> When you create an account, we collect your
                email address, name, and authentication credentials.
              </li>
              <li>
                <strong>Usage Data:</strong> We automatically collect information about how you
                interact with our services, including API calls, memory operations, and feature usage.
              </li>
              <li>
                <strong>Agent Data:</strong> The agent memory data you store through OpenZync is
                encrypted at rest and in transit. You retain full ownership of this data.
              </li>
              <li>
                <strong>Cookies:</strong> We use essential cookies for authentication and session
                management. Analytics cookies are used only with your consent.
              </li>
            </ul>
          </LegalSection>

          <LegalSection title="How We Use Your Information">
            <p>We use the collected information to:</p>
            <ul>
              <li>Provide, maintain, and improve our services</li>
              <li>Process transactions and manage your account</li>
              <li>Send technical notices, security alerts, and support messages</li>
              <li>Monitor usage patterns to improve performance and reliability</li>
              <li>Comply with legal obligations</li>
            </ul>
          </LegalSection>

          <LegalSection title="Data Security">
            <p>
              We implement industry-standard security measures to protect your data:
            </p>
            <ul>
              <li>Encryption at rest (AES-256) and in transit (TLS 1.3)</li>
              <li>Regular security audits and penetration testing</li>
              <li>Strict access controls and authentication requirements</li>
              <li>Automated threat detection and incident response</li>
            </ul>
          </LegalSection>

          <LegalSection title="Data Retention">
            <p>
              We retain your account information for as long as your account is active. Agent
              memory data is retained according to your configured retention policies. You can
              request deletion of your data at any time by contacting our support team.
            </p>
          </LegalSection>

          <LegalSection title="Third-Party Services">
            <p>
              OpenZync integrates with third-party services including graph databases and LLM
              providers. Data processed through these integrations is subject to their respective
              privacy policies. We recommend reviewing the privacy policies of any third-party
              services you connect to OpenZync.
            </p>
          </LegalSection>

          <LegalSection title="Analytics and Cookies">
            <p>
              We use Google Analytics 4 (GA4), a web analytics service provided by Google LLC
              (&ldquo;Google&rdquo;). GA4 uses first-party cookies to analyze how users interact
              with our website. The information generated by these cookies about your use of the
              website (including your IP address, browser type, pages visited, and time spent) is
              transmitted to and stored by Google on servers in the United States.
            </p>
            <p>
              We have enabled IP anonymization in GA4, which truncates your IP address before
              transmission. We have entered into a Data Processing Amendment with Google to ensure
              your data is processed in compliance with GDPR.
            </p>
            <p className="mt-4 font-semibold">What GA4 collects:</p>
            <ul>
              <li>Pages visited and time spent on each page</li>
              <li>Referring website or campaign</li>
              <li>Browser type, device type, and operating system</li>
              <li>Approximate geographic location (city-level)</li>
              <li>Clicks on links and buttons</li>
            </ul>
            <p className="mt-4 font-semibold">How we use this data:</p>
            <ul>
              <li>Understanding which content resonates with our audience</li>
              <li>Measuring marketing campaign effectiveness</li>
              <li>Identifying technical issues</li>
              <li>Improving user experience and site performance</li>
            </ul>
            <p className="mt-4 font-semibold">Your choices:</p>
            <ul>
              <li>You can opt out of GA4 analytics cookies via our Cookie Consent Banner</li>
              <li>You can install the Google Analytics Opt-out Browser Add-on</li>
              <li>You can configure your browser to block or delete cookies</li>
            </ul>
            <p className="mt-4">
              <strong>Data retention:</strong> We retain GA4 event data for 14 months. After this
              period, data is automatically deleted from Google&rsquo;s servers.
            </p>
          </LegalSection>

          <LegalSection title="Your Rights">
            <p>Depending on your jurisdiction, you may have the right to:</p>
            <ul>
              <li>Access the personal data we hold about you</li>
              <li>Correct inaccurate or incomplete data</li>
              <li>Delete your personal data</li>
              <li>Object to or restrict processing of your data</li>
              <li>Data portability</li>
              <li>Withdraw consent at any time</li>
            </ul>
          </LegalSection>

          <LegalSection title="Contact Us">
            <p>
              If you have questions about this Privacy Policy or our data practices, please
              contact us at{" "}
              <a href="mailto:privacy@openzync.tech" className="text-brand-300 hover:text-brand-200 transition-colors">
                privacy@openzync.tech
              </a>
              .
            </p>
          </LegalSection>
        </div>
      </section>

      <CtaSection />
    </>
  );
}

